server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Rota interna do Lambda Web Adapter — deve retornar 200
    location /events {
        return 200;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}